-- ============================================================
-- SAP HANA Inventory Management - Advanced Analytics Queries
-- ============================================================

-- ============================================================
-- QUERY 1: Real-time Inventory Status Dashboard
-- ============================================================
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    I.STOCK_QTY,
    P.REORDER_LEVEL,
    P.UNIT_PRICE,
    (I.STOCK_QTY * P.UNIT_PRICE) AS STOCK_VALUE,
    CASE 
        WHEN I.STOCK_QTY = 0 THEN 'OUT_OF_STOCK'
        WHEN I.STOCK_QTY < P.REORDER_LEVEL THEN 'REORDER_REQUIRED'
        WHEN I.STOCK_QTY <= (P.REORDER_LEVEL * 1.5) THEN 'LOW_STOCK'
        ELSE 'OPTIMAL'
    END AS STATUS
FROM INVENTORY_MGMT.PRODUCT P
JOIN INVENTORY_MGMT.INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
ORDER BY STATUS, STOCK_QTY ASC;

-- ============================================================
-- QUERY 2: ABC Analysis (Pareto Analysis)
-- ============================================================
WITH SALES_SUMMARY AS (
    SELECT 
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(S.SALE_AMOUNT) AS TOTAL_REVENUE,
        SUM(S.QUANTITY) AS TOTAL_UNITS_SOLD
    FROM INVENTORY_MGMT.PRODUCT P
    LEFT JOIN INVENTORY_MGMT.SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
),
CUMULATIVE_SALES AS (
    SELECT 
        *,
        SUM(TOTAL_REVENUE) OVER (ORDER BY TOTAL_REVENUE DESC) AS CUMULATIVE_REVENUE,
        SUM(TOTAL_REVENUE) OVER () AS TOTAL_REVENUE_ALL
    FROM SALES_SUMMARY
)
SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    TOTAL_REVENUE,
    TOTAL_UNITS_SOLD,
    ROUND((CUMULATIVE_REVENUE / TOTAL_REVENUE_ALL) * 100, 2) AS CUMULATIVE_REVENUE_PCT,
    CASE 
        WHEN (CUMULATIVE_REVENUE / TOTAL_REVENUE_ALL) <= 0.80 THEN 'A - High Value'
        WHEN (CUMULATIVE_REVENUE / TOTAL_REVENUE_ALL) <= 0.95 THEN 'B - Medium Value'
        ELSE 'C - Low Value'
    END AS PRODUCT_CLASSIFICATION
FROM CUMULATIVE_SALES
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================
-- QUERY 3: Inventory Turnover Rate by Category
-- ============================================================
SELECT 
    P.CATEGORY,
    COUNT(DISTINCT P.PRODUCT_ID) AS PRODUCT_COUNT,
    SUM(S.QUANTITY) AS TOTAL_SOLD,
    AVG(I.STOCK_QTY) AS AVG_STOCK_ON_HAND,
    CASE 
        WHEN AVG(I.STOCK_QTY) > 0 THEN 
            ROUND((SUM(S.QUANTITY) / AVG(I.STOCK_QTY)), 2)
        ELSE 0
    END AS TURNOVER_RATE,
    SUM(I.STOCK_QTY * P.UNIT_PRICE) AS TOTAL_CATEGORY_VALUE
FROM INVENTORY_MGMT.PRODUCT P
JOIN INVENTORY_MGMT.INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN INVENTORY_MGMT.SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TURNOVER_RATE DESC;

-- ============================================================
-- QUERY 4: Economic Order Quantity (EOQ) Recommendations
-- ============================================================
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.REORDER_LEVEL,
    SUM(S.QUANTITY) AS ANNUAL_DEMAND,
    ROUND(SQRT((2 * SUM(S.QUANTITY) * 50) / (P.UNIT_PRICE * 0.25)), 0) AS ECONOMIC_ORDER_QUANTITY,
    I.STOCK_QTY AS CURRENT_STOCK,
    CASE 
        WHEN I.STOCK_QTY < P.REORDER_LEVEL THEN 'URGENT'
        WHEN I.STOCK_QTY < (P.REORDER_LEVEL * 1.5) THEN 'SOON'
        ELSE 'NO_ACTION'
    END AS ORDER_URGENCY
FROM INVENTORY_MGMT.PRODUCT P
LEFT JOIN INVENTORY_MGMT.SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
JOIN INVENTORY_MGMT.INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE S.QUANTITY IS NOT NULL
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.REORDER_LEVEL, P.UNIT_PRICE, I.STOCK_QTY
ORDER BY ORDER_URGENCY DESC, P.PRODUCT_ID;

-- ============================================================
-- QUERY 5: Monthly Sales Trend Analysis
-- ============================================================
SELECT 
    TRUNC(S.SALE_DATE, 'MONTH') AS MONTH,
    P.CATEGORY,
    COUNT(S.SALE_ID) AS TRANSACTION_COUNT,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY,
    SUM(S.SALE_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(S.SALE_AMOUNT), 2) AS AVG_TRANSACTION_VALUE,
    COUNT(DISTINCT P.PRODUCT_ID) AS UNIQUE_PRODUCTS
FROM INVENTORY_MGMT.SALES S
JOIN INVENTORY_MGMT.PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY TRUNC(S.SALE_DATE, 'MONTH'), P.CATEGORY
ORDER BY MONTH DESC, TOTAL_REVENUE DESC;

-- ============================================================
-- QUERY 6: Dead Stock Analysis (Slow Moving Items)
-- ============================================================
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    I.STOCK_QTY,
    (I.STOCK_QTY * P.UNIT_PRICE) AS TIED_UP_CAPITAL,
    MAX(S.SALE_DATE) AS LAST_SALE_DATE,
    DATEDIFF(day, COALESCE(MAX(S.SALE_DATE), I.LAST_UPDATED), CURRENT_DATE) AS DAYS_WITHOUT_SALE,
    CASE 
        WHEN DATEDIFF(day, COALESCE(MAX(S.SALE_DATE), I.LAST_UPDATED), CURRENT_DATE) > 180 THEN 'DEAD_STOCK'
        WHEN DATEDIFF(day, COALESCE(MAX(S.SALE_DATE), I.LAST_UPDATED), CURRENT_DATE) > 90 THEN 'SLOW_MOVING'
        ELSE 'ACTIVE'
    END AS STOCK_STATUS
FROM INVENTORY_MGMT.PRODUCT P
JOIN INVENTORY_MGMT.INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN INVENTORY_MGMT.SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, I.STOCK_QTY, P.UNIT_PRICE, I.LAST_UPDATED
ORDER BY DAYS_WITHOUT_SALE DESC;

-- ============================================================
-- QUERY 7: Warehouse Efficiency Analysis
-- ============================================================
SELECT 
    I.WAREHOUSE_LOCATION,
    COUNT(DISTINCT P.PRODUCT_ID) AS TOTAL_SKUS,
    SUM(I.STOCK_QTY) AS TOTAL_UNITS,
    SUM(I.STOCK_QTY * P.UNIT_PRICE) AS WAREHOUSE_VALUE,
    ROUND(AVG(I.STOCK_QTY), 2) AS AVG_STOCK_PER_SKU,
    COUNT(CASE WHEN I.STOCK_QTY < P.REORDER_LEVEL THEN 1 END) AS LOW_STOCK_ITEMS,
    ROUND((COUNT(CASE WHEN I.STOCK_QTY < P.REORDER_LEVEL THEN 1 END) * 100.0 / COUNT(*)), 2) AS LOW_STOCK_PERCENTAGE
FROM INVENTORY_MGMT.INVENTORY I
JOIN INVENTORY_MGMT.PRODUCT P ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY I.WAREHOUSE_LOCATION
ORDER BY WAREHOUSE_VALUE DESC;

-- ============================================================
-- QUERY 8: Revenue Impact of Stock-Out Risk
-- ============================================================
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    I.STOCK_QTY,
    P.REORDER_LEVEL,
    SUM(S.SALE_AMOUNT) AS MONTHLY_REVENUE,
    CASE 
        WHEN I.STOCK_QTY = 0 THEN SUM(S.SALE_AMOUNT)
        ELSE 0
    END AS LOST_REVENUE_AT_RISK
FROM INVENTORY_MGMT.PRODUCT P
JOIN INVENTORY_MGMT.INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN INVENTORY_MGMT.SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
    AND S.SALE_DATE >= ADD_MONTHS(CURRENT_DATE, -1)
WHERE I.STOCK_QTY <= P.REORDER_LEVEL
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, I.STOCK_QTY, P.REORDER_LEVEL
ORDER BY LOST_REVENUE_AT_RISK DESC;
