-- Project 3: Key queries for Inventory Management & Stock Optimization (HANA SQL)

-- 1) Products below reorder level
SELECT p.PRODUCT_ID, p.SKU, p.NAME, p.REORDER_LEVEL, COALESCE(SUM(i.QUANTITY),0) AS ON_HAND
FROM PRODUCTS p
LEFT JOIN INVENTORY i ON i.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.SKU, p.NAME, p.REORDER_LEVEL
HAVING COALESCE(SUM(i.QUANTITY),0) <= COALESCE(p.REORDER_LEVEL,0)
ORDER BY ON_HAND ASC;

-- 2) Fast-moving vs slow-moving products (30-day usage)
SELECT p.PRODUCT_ID, p.SKU, p.NAME, COALESCE(SUM(CASE WHEN im.MOVEMENT_TYPE IN ('consumption','issue') THEN im.QUANTITY ELSE 0 END),0) AS USAGE_30D
FROM PRODUCTS p
LEFT JOIN INVENTORY_MOVEMENTS im ON im.PRODUCT_ID = p.PRODUCT_ID
  AND im.OCCURRED_AT >= ADD_DAYS(CURRENT_TIMESTAMP, -30)
GROUP BY p.PRODUCT_ID, p.SKU, p.NAME
ORDER BY USAGE_30D DESC;

-- 3) Stock valuation report (uses unit_price from order_items as source of price if available)
SELECT p.PRODUCT_ID, p.SKU, p.NAME, SUM(i.QUANTITY) AS TOTAL_QTY,
  AVG(oi.UNIT_PRICE) AS AVG_UNIT_PRICE,
  SUM(i.QUANTITY) * COALESCE(AVG(oi.UNIT_PRICE),0) AS ESTIMATED_VALUE
FROM PRODUCTS p
LEFT JOIN INVENTORY i ON i.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN ORDER_ITEMS oi ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.SKU, p.NAME
ORDER BY ESTIMATED_VALUE DESC;

-- 4) Reorder point calculation example (call procedure for a product)
-- CALL CALCULATE_REORDER_POINT( :product_id, 30, 1.65, ? );
