-- Sample data adapted for HANA schema (Project 3)

INSERT INTO PRODUCTS (SKU, NAME, CATEGORY, UNIT, REORDER_LEVEL, LEAD_TIME_DAYS) VALUES
('SKU-001','Widget A','Widgets','pcs',20,7),
('SKU-002','Widget B','Widgets','pcs',15,5),
('SKU-003','Gadget X','Gadgets','pcs',10,10);

INSERT INTO SUPPLIERS (NAME, CONTACT_EMAIL, PHONE) VALUES
('Acme Supplies','supply@acme.example','+1-555-0100'),
('Global Parts','parts@global.example','+1-555-0200');

INSERT INTO LOCATIONS (CODE, NAME, TYPE, ADDRESS) VALUES
('WH-001','Main Warehouse','warehouse','100 Supply St'),
('STORE-01','Retail Store 1','store','200 Market Ave');

INSERT INTO INVENTORY (PRODUCT_ID, LOCATION_ID, QUANTITY, RESERVED) VALUES
(1,1,100,5),
(2,1,50,0),
(3,1,8,2),
(1,2,5,1);

INSERT INTO SHIPMENTS (SHIPMENT_REF, SUPPLIER_ID, DEST_LOCATION_ID, EXPECTED_AT, STATUS) VALUES
('SHP-1001',1,1, ADD_DAYS(CURRENT_TIMESTAMP,2),'in_transit');

INSERT INTO ORDERS (ORDER_REF, ORDER_TYPE, LOCATION_ID, PLACED_AT, STATUS) VALUES
('ORD-9001','customer',2, ADD_DAYS(CURRENT_TIMESTAMP,-1),'fulfilled');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES
(1,1,2,9.99),
(1,3,1,19.99);

INSERT INTO INVENTORY_MOVEMENTS (PRODUCT_ID, FROM_LOCATION_ID, TO_LOCATION_ID, QUANTITY, MOVEMENT_TYPE) VALUES
(2,NULL,1,50,'receipt'),
(1,1,2,10,'transfer'),
(3,1,NULL,5,'consumption');
